services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Etc/UTC
    volumes:
      - ${LAB_PATH}/mount/heimdall/config:/config
    networks:
      caddy-io:
        ipv4_address: ${IP_HEIMDALL}
    restart: unless-stopped

networks:
  caddy-io:
    external: true
