services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: ${PUID}:${PGID}
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ${LAB_PATH}/mount/grafana/lib:/var/lib/grafana
      - ${LAB_PATH}/mount/grafana/data:/etc/grafana/provisioning/datasources
    networks:
      grafana-io:
        ipv4_address: ${IP_GRAFANA_GRAFANA}
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: monitoring_prometheus
    user: ${PUID}:${PGID}
    volumes:
      - ${LAB_PATH}/mount/monitoring/prometheus/config:/etc/prometheus/
      - ${LAB_PATH}/mount/monitoring/prometheus/data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      grafana-io:
        ipv4_address: ${IP_PROMETHEUS_GRAFANA}
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:latest
    container_name: monitoring_node_exporter
    networks:
      grafana-io:
        ipv4_address: ${IP_NODE-EXPORTER_GRAFANA}
    restart: unless-stopped

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: monitoring_cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      grafana-io:
        ipv4_address: ${IP_CADVISOR_GRAFANA}
    restart: unless-stopped

networks:
  grafana-io:
    external: true
