services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - ${LAB_PATH}/mount/postgres:/var/lib/postgresql/data
    command: postgres
      -c max_connections=300
      -c shared_buffers=2560MB
      -c effective_cache_size=7680MB
      -c maintenance_work_mem=640MB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
      -c default_statistics_target=100
      -c random_page_cost=1.1
      -c effective_io_concurrency=200
      -c work_mem=4369kB
      -c huge_pages=off
      -c min_wal_size=2GB
      -c max_wal_size=8GB
      -c max_worker_processes=4
      -c max_parallel_workers_per_gather=2
      -c max_parallel_workers=4
      -c max_parallel_maintenance_workers=2
    deploy:
      resources:
        limits:
          memory: 12G
        reservations:
          memory: 12G
    memswap_limit: 16G
    networks:
      caddy-io:
        ipv4_address: ${IP_POSTGRES}
    restart: unless-stopped

networks:
  caddy-io:
    external: true
